'use client'

import { useEffect, useState, useCallback } from 'react'
import { api, type Settings } from '@/lib/api'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Slider } from '@/components/ui/slider'
import { Skeleton } from '@/components/ui/skeleton'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog'
import { Volume2, Save, Trash2, Sun, Moon, Monitor } from 'lucide-react'
import { toast } from 'sonner'
import { useTheme } from 'next-themes'
import { getEnglishVoices, speak, isSpeechSupported } from '@/lib/tts'

export function SettingsView() {
  const [settings, setSettings] = useState<Settings | null>(null)
  const [voices, setVoices] = useState<SpeechSynthesisVoice[]>([])
  const [saving, setSaving] = useState(false)
  const { setTheme, theme } = useTheme()

  useEffect(() => {
    let mounted = true
    ;(async () => {
      const s = await api.getSettings()
      if (mounted) setSettings(s)
    })()
    return () => { mounted = false }
  }, [])

  useEffect(() => {
    if (typeof window === 'undefined') return
    const update = () => setVoices(getEnglishVoices())
    const id = setTimeout(update, 100)
    const handler = () => { update() }
    if ('speechSynthesis' in window) {
      window.speechSynthesis.onvoiceschanged = handler
    }
    return () => {
      clearTimeout(id)
      if ('speechSynthesis' in window) window.speechSynthesis.onvoiceschanged = null
    }
  }, [])

  const handleSave = useCallback(async () => {
    if (!settings) return
    setSaving(true)
    try {
      await api.updateSettings(settings)
      toast.success('Settings saved')
    } catch (e) {
      toast.error('Failed to save settings')
    } finally {
      setSaving(false)
    }
  }, [settings])

  if (!settings) {
    return (
      <div className="space-y-4 max-w-3xl">
        <Skeleton className="h-8 w-48" />
        <Skeleton className="h-48 w-full" />
        <Skeleton className="h-32 w-full" />
        <Skeleton className="h-32 w-full" />
        <Skeleton className="h-40 w-full" />
        <Skeleton className="h-10 w-32 ml-auto" />
      </div>
    )
  }

  return (
    <div className="space-y-4 max-w-3xl">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Settings</h1>
        <p className="text-sm text-muted-foreground mt-0.5">Tune your local learning environment.</p>
      </div>

      {/* TTS */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <Volume2 className="h-4 w-4" />
            Browser Speech Synthesis
          </CardTitle>
          <CardDescription>
            Pronunciation is generated by your browser/OS. No external API calls.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <Label>Voice</Label>
            <Select
              value={settings.ttsVoice || 'default'}
              onValueChange={(v) => setSettings({ ...settings, ttsVoice: v === 'default' ? '' : v })}
            >
              <SelectTrigger>
                <SelectValue placeholder="System default" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="default">System default</SelectItem>
                {voices.map((v) => (
                  <SelectItem key={v.name} value={v.name}>
                    {v.name} ({v.lang})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {voices.length === 0 && (
              <p className="text-xs text-amber-600 mt-1.5">
                No English voices found. Your OS may need voices installed.
              </p>
            )}
          </div>

          <div>
            <Label>Speech rate: {settings.ttsRate.toFixed(1)}×</Label>
            <Slider
              min={0.5}
              max={2}
              step={0.1}
              value={[settings.ttsRate]}
              onValueChange={([v]) => setSettings({ ...settings, ttsRate: v })}
              className="mt-2"
            />
          </div>

          <Button
            variant="outline"
            onClick={() => {
              const ok = speak('Hello, this is a sample pronunciation.', { voice: settings.ttsVoice, rate: settings.ttsRate })
              if (!ok) toast.error('TTS not available. Try a different voice or check OS speech settings.')
            }}
          >
            <Volume2 className="h-4 w-4 mr-1.5" /> Test voice
          </Button>

          <details className="text-xs text-muted-foreground border rounded-lg p-3">
            <summary className="cursor-pointer font-medium">TTS diagnostics</summary>
            <div className="mt-2 space-y-1">
              <div>API supported: {isSpeechSupported() ? '✓' : '✗'}</div>
              <div>English voices found: {voices.length}</div>
              {voices.length > 0 && (
                <div className="mt-1">
                  Available voices:
                  <ul className="list-disc pl-4 mt-0.5">
                    {voices.slice(0, 5).map((v) => (
                      <li key={v.name}>{v.name} ({v.lang})</li>
                    ))}
                    {voices.length > 5 && <li>…and {voices.length - 5} more</li>}
                  </ul>
                </div>
              )}
              {voices.length === 0 && (
                <p className="text-amber-600">
                  No voices detected. On Linux, install speech-dispatcher or use Firefox.
                </p>
              )}
            </div>
          </details>
        </CardContent>
      </Card>

      {/* Daily goal */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Daily Goal</CardTitle>
          <CardDescription>Target number of reviews per day</CardDescription>
        </CardHeader>
        <CardContent>
          <Input
            type="number"
            min={1}
            max={200}
            value={settings.dailyGoal}
            onChange={(e) => setSettings({ ...settings, dailyGoal: parseInt(e.target.value, 10) || 1 })}
            className="w-32"
          />
        </CardContent>
      </Card>

      {/* Theme */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Theme</CardTitle>
          <CardDescription>Choose how LexiLearn looks</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-3 gap-2">
            {([
              { value: 'light', label: 'Light', icon: Sun },
              { value: 'dark', label: 'Dark', icon: Moon },
              { value: 'system', label: 'System', icon: Monitor },
            ] as const).map((t) => {
              const Icon = t.icon
              const isActive = (theme ?? 'system') === t.value
              return (
                <Button
                  key={t.value}
                  variant={isActive ? 'default' : 'outline'}
                  onClick={() => {
                    setTheme(t.value)
                    api.updateSettings({ theme: t.value })
                  }}
                  className="flex-col h-auto py-3"
                >
                  <Icon className="h-4 w-4 mb-1" />
                  <span className="text-xs">{t.label}</span>
                </Button>
              )
            })}
          </div>
        </CardContent>
      </Card>

      {/* Danger zone */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base text-destructive">Danger Zone</CardTitle>
          <CardDescription>These actions cannot be undone.</CardDescription>
        </CardHeader>
        <CardContent>
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button variant="outline" className="text-destructive">
                <Trash2 className="h-4 w-4 mr-1.5" /> Reset all progress
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Reset all progress?</AlertDialogTitle>
                <AlertDialogDescription>
                  This will erase all SRS cards, review logs, quiz sessions, XP, streaks, and settings. Word decks and dictionary data are preserved.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction
                  className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                  onClick={async () => {
                    try {
                      await api.resetProgress()
                      toast.success('Progress reset')
                      window.location.reload()
                    } catch (e) {
                      toast.error('Reset failed')
                    }
                  }}
                >
                  Reset everything
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </CardContent>
      </Card>

      <div className="flex justify-end">
        <Button onClick={handleSave} disabled={saving}>
          <Save className="h-4 w-4 mr-1.5" />
          {saving ? 'Saving…' : 'Save settings'}
        </Button>
      </div>
    </div>
  )
}
