// LexiLearn seed script — populates 4 decks with curated vocabulary
// Run with: pnpm db:seed

import Database from 'better-sqlite3'
import { drizzle } from 'drizzle-orm/better-sqlite3'
import { resolveDbPath } from '../src/db/env'
import * as schema from '../src/db/schema'
import { createId } from '../src/db/id'

const sqlite = new Database(resolveDbPath())
sqlite.pragma('foreign_keys = ON')
export const db = drizzle(sqlite, { schema })
const { deck, word, srsCard, reviewLog, quizSession, appStat } = schema

type SeedWord = {
  word: string
  pos?: string
  ipa?: string
  syllables?: string[]
  cefr?: string
  definitions?: { pos: string; text: string }[]
  examples?: string[]
  synonyms?: string[]
  antonyms?: string[]
  etymology?: string
  amharic?: string
}

// ---------- Common 500 (starter — first 80 most useful words beyond A1) ----------
const COMMON: SeedWord[] = [
  { word: "abundant", pos: "adjective", ipa: "/əˈbʌn.dənt/", syllables: ["a","bun","dant"], cefr: "B2",
    definitions: [{ pos: "adj", text: "Existing in large quantities; plentiful." }],
    examples: ["The region has abundant natural resources.", "Fish are abundant in these waters."],
    synonyms: ["plentiful", "ample", "copious"], antonyms: ["scarce", "rare"],
    etymology: "From Latin abundant- 'overflowing'.",
    amharic: "በብዛት የሚገኝ; የተትረፈረፈ" },
  { word: "brisk", pos: "adjective", ipa: "/brɪsk/", syllables: ["brisk"], cefr: "B1",
    definitions: [{ pos: "adj", text: "Quick and active; fast-paced." }],
    examples: ["Business has been brisk this morning.", "We took a brisk walk."],
    synonyms: ["lively", "quick", "energetic"], antonyms: ["sluggish", "slow"],
    amharic: "ፈጣን እና ንቁ; በሃይል የተሞላ" },
  { word: "cautious", pos: "adjective", ipa: "/ˈkɔː.ʃəs/", syllables: ["cau","tious"], cefr: "B1",
    definitions: [{ pos: "adj", text: "Being careful to avoid danger or mistakes." }],
    examples: ["She is cautious about sharing personal data.", "A cautious driver saves lives."],
    synonyms: ["careful", "wary", "prudent"], antonyms: ["reckless", "rash"],
    amharic: "ጠንቃቃ; አደጋን ለማስወገድ የሚጠነቀቅ" },
  { word: "diligent", pos: "adjective", ipa: "/ˈdɪl.ɪ.dʒənt/", syllables: ["dil","i","gent"], cefr: "B2",
    definitions: [{ pos: "adj", text: "Showing care and effort in work or duty." }],
    examples: ["He is a diligent student who never misses homework.", "Diligent research takes time."],
    synonyms: ["hardworking", "industrious", "assiduous"], antonyms: ["lazy", "negligent"],
    amharic: "ታታሪ; በስራ ላይ ጥንቃቄ እና ጥረት የሚያደርግ" },
  { word: "elaborate", pos: "verb", ipa: "/ɪˈlæb.ər.eɪt/", syllables: ["e","lab","o","rate"], cefr: "B2",
    definitions: [
      { pos: "verb", text: "To develop or present in detail." },
      { pos: "adj", text: "Detailed and carefully planned." }
    ],
    examples: ["Could you elaborate on your proposal?", "They prepared an elaborate meal."],
    synonyms: ["expand", "detail", "intricate"], antonyms: ["simplify", "outline"],
    amharic: "በዝርዝር ማብራራት; የተወሳሰበ እቅድ" },
  { word: "frequent", pos: "adjective", ipa: "/ˈfriː.kwənt/", syllables: ["fre","quent"], cefr: "B1",
    definitions: [{ pos: "adj", text: "Happening often." }],
    examples: ["Frequent exercise improves health.", "He is a frequent visitor."],
    synonyms: ["common", "regular", "recurring"], antonyms: ["rare", "occasional"],
    amharic: "ተደጋጋሚ; በተደጋጋሚ የሚከሰት" },
  { word: "genuine", pos: "adjective", ipa: "/ˈdʒen.ju.ɪn/", syllables: ["gen","u","ine"], cefr: "B2",
    definitions: [{ pos: "adj", text: "Truly what it appears to be; authentic." }],
    examples: ["This is a genuine leather bag.", "She showed genuine concern."],
    synonyms: ["authentic", "real", "sincere"], antonyms: ["fake", "artificial"],
    amharic: "እውነተኛ; ሐቀኛ; የተፈጥሮ" },
  { word: "hesitate", pos: "verb", ipa: "/ˈhez.ɪ.teɪt/", syllables: ["hes","i","tate"], cefr: "B2",
    definitions: [{ pos: "verb", text: "To pause before acting due to uncertainty." }],
    examples: ["Don't hesitate to ask if you need help.", "He hesitated before answering."],
    synonyms: ["pause", "waver", "delay"], antonyms: ["proceed", "act"],
    amharic: "ማመነታት; ከመወሰን በፊት ማቅማል" },
  { word: "inevitable", pos: "adjective", ipa: "/ɪnˈev.ɪ.tə.bəl/", syllables: ["in","ev","i","ta","ble"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Certain to happen; unavoidable." }],
    examples: ["Change is inevitable.", "Given his speed, victory seemed inevitable."],
    synonyms: ["unavoidable", "inescapable", "certain"], antonyms: ["avoidable", "uncertain"],
    amharic: "የማይቀር; መሆኑ አይቀሬ" },
  { word: "judicious", pos: "adjective", ipa: "/dʒuˈdɪʃ.əs/", syllables: ["ju","di","cious"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Showing good judgment; wise." }],
    examples: ["A judicious use of resources helped the company survive.", "She made a judicious decision."],
    synonyms: ["wise", "prudent", "sensible"], antonyms: ["foolish", "imprudent"],
    amharic: "አስተዋይ; ጥሩ ውሳኔ የሚያደርግ" },
  { word: "keen", pos: "adjective", ipa: "/kiːn/", syllables: ["keen"], cefr: "B2",
    definitions: [{ pos: "adj", text: "Eager; having sharp perception." }],
    examples: ["She is keen to learn new skills.", "He has a keen eye for detail."],
    synonyms: ["eager", "sharp", "enthusiastic"], antonyms: ["indifferent", "dull"],
    amharic: "ከፍተኛ ፍላጎት ያለው; ስለታም አመለካከት" },
  { word: "lucid", pos: "adjective", ipa: "/ˈluː.sɪd/", syllables: ["lu","cid"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Clear and easy to understand." }],
    examples: ["The professor gave a lucid explanation.", "He wrote in a lucid style."],
    synonyms: ["clear", "coherent", "intelligible"], antonyms: ["obscure", "confusing"],
    amharic: "ግልጽ; ለመረዳት የሚቻል" },
  { word: "meticulous", pos: "adjective", ipa: "/məˈtɪk.jə.ləs/", syllables: ["me","tic","u","lous"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Showing great attention to detail; very careful." }],
    examples: ["She kept meticulous records of every transaction.", "A meticulous craftsman produces fine work."],
    synonyms: ["thorough", "scrupulous", "precise"], antonyms: ["careless", "sloppy"],
    amharic: "ጥንቃቄ የሞላበት; ለዝርዝር ከፍተኛ ትኩረት የሚሰጥ" },
  { word: "notable", pos: "adjective", ipa: "/ˈnəʊ.tə.bəl/", syllables: ["no","ta","ble"], cefr: "B2",
    definitions: [{ pos: "adj", text: "Worthy of attention; remarkable." }],
    examples: ["She gave a notable performance.", "There has been a notable improvement."],
    synonyms: ["remarkable", "significant", "striking"], antonyms: ["unremarkable", "ordinary"],
    amharic: "ታዋቂ; ትኩረት የሚስብ; የሚታወቅ" },
  { word: "obscure", pos: "adjective", ipa: "/əbˈskjʊər/", syllables: ["ob","scure"], cefr: "C1",
    definitions: [
      { pos: "adj", text: "Not clearly known or expressed." },
      { pos: "verb", text: "To keep from being seen; conceal." }
    ],
    examples: ["The meaning of the poem is obscure.", "Clouds obscured the sun."],
    synonyms: ["unclear", "vague", "hidden"], antonyms: ["clear", "obvious"],
    amharic: "ደብዛዛ; ግልጽ ያልሆነ; መደበቅ" },
  { word: "prudent", pos: "adjective", ipa: "/ˈpruː.dənt/", syllables: ["pru","dent"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Acting with care for the future." }],
    examples: ["It is prudent to save for retirement.", "She gave a prudent reply."],
    synonyms: ["sensible", "cautious", "judicious"], antonyms: ["imprudent", "rash"],
    amharic: "አስተዋይ; ለወደፊቱ በማሰብ የሚንቀሳቀስ" },
  { word: "quaint", pos: "adjective", ipa: "/kweɪnt/", syllables: ["quaint"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Attractively unusual or old-fashioned." }],
    examples: ["They stayed in a quaint cottage.", "The village has a quaint charm."],
    synonyms: ["picturesque", "old-fashioned", "charming"], antonyms: ["modern", "ordinary"],
    amharic: "ልዩ እና ማራኪ; ያረጀ ውበት ያለው" },
  { word: "resilient", pos: "adjective", ipa: "/rɪˈzɪl.i.ənt/", syllables: ["re","sil","i","ent"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Able to recover quickly from difficulties." }],
    examples: ["Children are often remarkably resilient.", "A resilient economy recovers fast."],
    synonyms: ["tough", "adaptable", "hardy"], antonyms: ["fragile", "vulnerable"],
    amharic: "ጠንካራ; ከችግር በፍጥነት መልሶ የማገገም ችሎታ ያለው" },
  { word: "scrutinize", pos: "verb", ipa: "/ˈskruː.tɪ.naɪz/", syllables: ["scru","ti","nize"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To examine carefully and critically." }],
    examples: ["The committee scrutinized every line of the contract.", "He scrutinized her expression."],
    synonyms: ["examine", "inspect", "analyze"], antonyms: ["skim", "ignore"],
    amharic: "በጥንቃቄ መመርመር; ማጣራት" },
  { word: "tedious", pos: "adjective", ipa: "/ˈtiː.di.əs/", syllables: ["te","di","ous"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Too long, slow, or dull; tiresome." }],
    examples: ["Filing paperwork can be tedious.", "It was a tedious lecture."],
    synonyms: ["boring", "monotonous", "wearisome"], antonyms: ["exciting", "stimulating"],
    amharic: "አሰልቺ; ረጅም እና ደካማ የሚያደርግ" },
  { word: "ubiquitous", pos: "adjective", ipa: "/juːˈbɪk.wɪ.təs/", syllables: ["u","biqu","i","tous"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Present, appearing, or found everywhere." }],
    examples: ["Smartphones have become ubiquitous.", "Coffee shops are ubiquitous in this city."],
    synonyms: ["omnipresent", "universal", "pervasive"], antonyms: ["rare", "scarce"],
    amharic: "በየቦታው የሚገኝ; ሁሉም ቦታ የሚታይ" },
  { word: "vivid", pos: "adjective", ipa: "/ˈvɪv.ɪd/", syllables: ["viv","id"], cefr: "B2",
    definitions: [{ pos: "adj", text: "Producing strong, clear images in the mind." }],
    examples: ["She has vivid memories of childhood.", "The painting uses vivid colors."],
    synonyms: ["bright", "striking", "lifelike"], antonyms: ["dull", "faint"],
    amharic: "ግልጽ እና ሕያው; በአእምሮ ውስጥ ግልጽ ምስል የሚፈጥር" },
  { word: "wary", pos: "adjective", ipa: "/ˈweə.ri/", syllables: ["wa","ry"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Cautious about danger; watchful." }],
    examples: ["Be wary of strangers offering deals.", "She gave him a wary look."],
    synonyms: ["cautious", "wary", "leery"], antonyms: ["trusting", "careless"],
    amharic: "ጠንቃቃ; ለአደጋ የሚጠነቀቅ" },
  { word: "zealous", pos: "adjective", ipa: "/ˈzel.əs/", syllables: ["zeal","ous"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Showing great energy or enthusiasm." }],
    examples: ["She is a zealous supporter of the cause.", "He was zealous in his duties."],
    synonyms: ["passionate", "fervent", "enthusiastic"], antonyms: ["apathetic", "indifferent"],
    amharic: "ታዳጊ; ከፍተኛ ጉጉት እና ቅንዓት ያለው" },
  { word: "ambiguous", pos: "adjective", ipa: "/æmˈbɪɡ.ju.əs/", syllables: ["am","big","u","ous"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Open to more than one interpretation." }],
    examples: ["His answer was deliberately ambiguous.", "The law is ambiguous on this point."],
    synonyms: ["unclear", "vague", "equivocal"], antonyms: ["clear", "explicit"],
    amharic: "አሻሚ; ከአንድ በላይ ትርጉም ያለው" },
  { word: "benevolent", pos: "adjective", ipa: "/bəˈnev.əl.ənt/", syllables: ["be","nev","o","lent"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Well meaning and kindly." }],
    examples: ["He was a benevolent ruler.", "She gave him a benevolent smile."],
    synonyms: ["kind", "generous", "compassionate"], antonyms: ["malevolent", "cruel"],
    amharic: "ደግ; ለጋስ; ቸር" },
  { word: "compromise", pos: "noun", ipa: "/ˈkɒm.prə.maɪz/", syllables: ["com","pro","mise"], cefr: "B2",
    definitions: [
      { pos: "noun", text: "An agreement reached by each side making concessions." },
      { pos: "verb", text: "To settle a dispute by mutual concession." }
    ],
    examples: ["They reached a compromise after hours of talk.", "Don't compromise your principles."],
    synonyms: ["agreement", "settlement"], antonyms: ["dispute", "conflict"],
    amharic: "ስምምነት; መግባባት; ሁለቱም ወገኖች የሚስማሙበት" },
  { word: "dilemma", pos: "noun", ipa: "/dɪˈlem.ə/", syllables: ["di","lem","ma"], cefr: "C1",
    definitions: [{ pos: "noun", text: "A situation with a difficult choice between options." }],
    examples: ["She faced a moral dilemma.", "The manager is in a dilemma over layoffs."],
    synonyms: ["predicament", "quandary"], antonyms: ["solution"],
    amharic: "አጣብቂኝ; ከባድ ምርጫ የሚጠይቅ ሁኔታ" },
  { word: "empathy", pos: "noun", ipa: "/ˈem.pə.θi/", syllables: ["em","pa","thy"], cefr: "C1",
    definitions: [{ pos: "noun", text: "The ability to share another's feelings." }],
    examples: ["Good therapists have deep empathy.", "She showed empathy toward the victims."],
    synonyms: ["understanding", "compassion"], antonyms: ["indifference", "coldness"],
    amharic: "ርኅራኄ; የሌላውን ስሜት የመረዳት ችሎታ" },
  { word: "frugal", pos: "adjective", ipa: "/ˈfruː.ɡəl/", syllables: ["fru","gal"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Sparing with money or food." }],
    examples: ["He lived a frugal life.", "A frugal meal of bread and cheese."],
    synonyms: ["thrifty", "economical"], antonyms: ["extravagant", "wasteful"],
    amharic: "ቆጣቢ; በገንዘብ ወይም በምግብ ላይ የሚቆጥብ" },
  { word: "gregarious", pos: "adjective", ipa: "/ɡrɪˈɡeə.ri.əs/", syllables: ["gre","gar","i","ous"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Fond of company; sociable." }],
    examples: ["She is a gregarious host.", "Dolphins are gregarious animals."],
    synonyms: ["sociable", "outgoing"], antonyms: ["introverted", "solitary"],
    amharic: "ተግባቢ; ማህበራዊ ግንኙነት የሚወድ" },
  { word: "haughty", pos: "adjective", ipa: "/ˈhɔː.ti/", syllables: ["haugh","ty"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Arrogantly superior and disdainful." }],
    examples: ["She gave him a haughty stare.", "His haughty manner offended many."],
    synonyms: ["arrogant", "proud"], antonyms: ["humble", "modest"],
    amharic: "ትዕቢተኛ; እብሪተኛ" },
  { word: "intrepid", pos: "adjective", ipa: "/ɪnˈtrep.ɪd/", syllables: ["in","trep","id"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Fearless; adventurous." }],
    examples: ["The intrepid explorer crossed the desert.", "An intrepid reporter uncovered the scandal."],
    synonyms: ["fearless", "bold", "courageous"], antonyms: ["timid", "cowardly"],
    amharic: "ያልፈራ; ደፋር; ጀብደኛ" },
  { word: "jovial", pos: "adjective", ipa: "/ˈdʒəʊ.vi.əl/", syllables: ["jo","vi","al"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Cheerful and friendly." }],
    examples: ["He is in a jovial mood tonight.", "A jovial host made everyone welcome."],
    synonyms: ["merry", "cheerful", "genial"], antonyms: ["gloomy", "morose"],
    amharic: "ደስተኛ; ምስጉስ; ወዳጃዊ" },
  { word: "kindle", pos: "verb", ipa: "/ˈkɪn.dəl/", syllables: ["kin","dle"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To light or inspire; to start burning." }],
    examples: ["Her speech kindled hope in the crowd.", "He kindled a fire in the hearth."],
    synonyms: ["ignite", "inspire", "arouse"], antonyms: ["extinguish", "dampen"],
    amharic: "ማብራት; ማነሳሳት; እሳት ማስነሳት" },
  { word: "languid", pos: "adjective", ipa: "/ˈlæŋ.ɡwɪd/", syllables: ["lan","guid"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Lacking energy; slow and relaxed." }],
    examples: ["She gave a languid wave.", "The afternoon was hot and languid."],
    synonyms: ["sluggish", "lethargic"], antonyms: ["energetic", "brisk"],
    amharic: "ደካማ; እንቅስቃሴ የሌለው; ዘና ያለ" },
  { word: "meander", pos: "verb", ipa: "/miˈæn.dər/", syllables: ["me","an","der"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To follow a winding course; wander." }],
    examples: ["The river meanders through the valley.", "He meandered through the old town."],
    synonyms: ["wander", "drift", "stroll"], antonyms: ["rush", "hurry"],
    amharic: "መንከራተት; ጠመዝማዛ መንገድ መከተል" },
  { word: "nostalgia", pos: "noun", ipa: "/nɒsˈtæl.dʒə/", syllables: ["nos","tal","gia"], cefr: "C1",
    definitions: [{ pos: "noun", text: "A sentimental longing for the past." }],
    examples: ["Hearing the song filled her with nostalgia.", "Old photos evoke nostalgia."],
    synonyms: ["wistfulness", "reminiscence"], antonyms: ["anticipation"],
    amharic: "ናፍቆት; ያለፈውን በሀዘን መናፈቅ" },
  { word: "obstinate", pos: "adjective", ipa: "/ˈɒb.stɪ.nət/", syllables: ["ob","sti","nate"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Stubbornly refusing to change one's opinion." }],
    examples: ["He is too obstinate to admit he's wrong.", "An obstinate cough lingered for weeks."],
    synonyms: ["stubborn", "headstrong"], antonyms: ["flexible", "compliant"],
    amharic: "ግትር; የራሱን አመለካከት ለመቀየር የማይፈልግ" },
  { word: "panacea", pos: "noun", ipa: "/ˌpæn.əˈsiː.ə/", syllables: ["pan","a","ce","a"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A remedy for all difficulties or diseases." }],
    examples: ["Technology is not a panacea for education.", "They sought a panacea for all ills."],
    synonyms: ["cure-all", "universal remedy"], antonyms: ["ineffective remedy"],
    amharic: "መድኃኒት ሁሉ; ለሁሉም ችግር መፍትሄ" },
  { word: "quintessential", pos: "adjective", ipa: "/ˌkwɪn.tɪˈsen.ʃəl/", syllables: ["quin","tes","sen","tial"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Representing the most perfect example." }],
    examples: ["She is the quintessential professional.", "A quintessential English afternoon."],
    synonyms: ["archetypal", "definitive"], antonyms: ["atypical"],
    amharic: "ምሳሌያዊ; ፍጹም ምሳሌ የሆነ" },
  { word: "ravenous", pos: "adjective", ipa: "/ˈræv.ən.əs/", syllables: ["rav","en","ous"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Extremely hungry; greedy." }],
    examples: ["After the hike, I was ravenous.", "A ravenous reader devours books."],
    synonyms: ["starving", "famished"], antonyms: ["full", "sated"],
    amharic: "በጣም የተራበ; ሰግነት ያለው" },
  { word: "serene", pos: "adjective", ipa: "/səˈriːn/", syllables: ["se","rene"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Calm, peaceful, and untroubled." }],
    examples: ["The lake was serene at dawn.", "She has a serene expression."],
    synonyms: ["tranquil", "placid", "calm"], antonyms: ["agitated", "turbulent"],
    amharic: "ጸጥ ያለ; ሰላማዊ; የተረጋጋ" },
  { word: "tranquil", pos: "adjective", ipa: "/ˈtræŋ.kwɪl/", syllables: ["tran","quil"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Free from disturbance; calm." }],
    examples: ["A tranquil garden surrounded the house.", "She led a tranquil life."],
    synonyms: ["peaceful", "serene", "placid"], antonyms: ["chaotic", "noisy"],
    amharic: "ረጋ ያለ; ከረብሻ ነፃ የሆነ" },
  { word: "unctuous", pos: "adjective", ipa: "/ˈʌŋk.tʃu.əs/", syllables: ["unc","tu","ous"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Excessively flattering; oily." }],
    examples: ["The waiter's unctuous manner annoyed us.", "An unctuous smile hid his true intent."],
    synonyms: ["sycophantic", "oily", "smarmy"], antonyms: ["sincere", "genuine"],
    amharic: "አይብ የሚባል; ከልክ ያለፈ ማሳሳት" },
  { word: "verbose", pos: "adjective", ipa: "/vəːˈbəʊs/", syllables: ["ver","bose"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Using more words than needed; wordy." }],
    examples: ["His verbose report bored the board.", "Try to be less verbose."],
    synonyms: ["wordy", "long-winded"], antonyms: ["concise", "terse"],
    amharic: "ረጅም ንግግር; ከሚያስፈልገው በላይ ቃላትን የሚጠቀም" },
  { word: "whimsical", pos: "adjective", ipa: "/ˈwɪm.zɪ.kəl/", syllables: ["whim","si","cal"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Playfully quaint; fanciful." }],
    examples: ["The film has a whimsical charm.", "She wore a whimsical hat."],
    synonyms: ["fanciful", "playful", "quirky"], antonyms: ["serious", "solemn"],
    amharic: "ልዩ እና አስቂኝ; የማይታሰብ" },
  { word: "zenith", pos: "noun", ipa: "/ˈziː.nɪθ/", syllables: ["ze","nith"], cefr: "C1",
    definitions: [{ pos: "noun", text: "The highest point; peak." }],
    examples: ["She reached the zenith of her career.", "The empire was at its zenith."],
    synonyms: ["peak", "apex", "pinnacle"], antonyms: ["nadir", "bottom"],
    amharic: "ከፍተኛ ደረጃ; ጫፍ; የላቀ ቦታ" },
  { word: "aesthetic", pos: "adjective", ipa: "/iːsˈθet.ɪk/", syllables: ["aes","thet","ic"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Concerned with beauty or art." }],
    examples: ["The building has aesthetic appeal.", "She has a strong aesthetic sense."],
    synonyms: ["artistic", "tasteful"], antonyms: ["utilitarian", "plain"],
    amharic: "ውበትን የሚመለከት; የጥበብ ውበት" },
  { word: "bolster", pos: "verb", ipa: "/ˈbəʊl.stər/", syllables: ["bol","ster"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To support or strengthen." }],
    examples: ["The new data bolsters our theory.", "A snack will bolster your energy."],
    synonyms: ["strengthen", "support", "reinforce"], antonyms: ["undermine", "weaken"],
    amharic: "ማጠናከር; መደገፍ; ማበረታታት" },
  { word: "candid", pos: "adjective", ipa: "/ˈkæn.dɪd/", syllables: ["can","did"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Truthful and straightforward; frank." }],
    examples: ["She gave a candid interview.", "He was candid about his mistakes."],
    synonyms: ["frank", "honest", "outspoken"], antonyms: ["evasive", "guarded"],
    amharic: "ሐቀኛ; ግልጽ; ያለ ማሸማጠቅ የሚናገር" },
  { word: "daunting", pos: "adjective", ipa: "/ˈdɔːn.tɪŋ/", syllables: ["daunt","ing"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Seeming difficult to deal with." }],
    examples: ["The climb looked daunting.", "She faced a daunting workload."],
    synonyms: ["intimidating", "formidable"], antonyms: ["easy", "inviting"],
    amharic: "ፈታኝ; አስፈሪ; ለመቋቋም ከባድ" },
  { word: "eloquent", pos: "adjective", ipa: "/ˈel.ə.kwənt/", syllables: ["el","o","quent"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Fluent and persuasive in speaking or writing." }],
    examples: ["She gave an eloquent speech.", "His silence was eloquent of grief."],
    synonyms: ["articulate", "fluent", "persuasive"], antonyms: ["inarticulate", "halting"],
    amharic: "አነጋጋሪ; ማራኪ ንግግር ያለው; አሳማኝ" },
  { word: "fastidious", pos: "adjective", ipa: "/fæˈstɪd.i.əs/", syllables: ["fas","tid","i","ous"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Very attentive to detail; hard to please." }],
    examples: ["She is fastidious about cleanliness.", "A fastidious editor catches every error."],
    synonyms: ["meticulous", "fussy", "exacting"], antonyms: ["careless", "easygoing"],
    amharic: "ጥንቃቄ የሞላበት; ማርካት የሚከብደው" },
  { word: "grudging", pos: "adjective", ipa: "/ˈɡrʌdʒ.ɪŋ/", syllables: ["grudg","ing"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Given reluctantly; unwilling." }],
    examples: ["He gave grudging approval.", "She offered grudging admiration."],
    synonyms: ["reluctant", "unwilling"], antonyms: ["enthusiastic", "willing"],
    amharic: "ሳይወድ; በግዴታ የተሰጠ" },
  { word: "harbor", pos: "noun", ipa: "/ˈhɑː.bər/", syllables: ["har","bor"], cefr: "B2",
    definitions: [
      { pos: "noun", text: "A place on the coast where ships dock." },
      { pos: "verb", text: "To hold a thought or feeling; to shelter." }
    ],
    examples: ["The boats rested in the harbor.", "He harbors dreams of writing a novel."],
    synonyms: ["port", "haven", "shelter"], antonyms: ["expose"],
    amharic: "ወደብ; መሸሸጊያ; ሀሳብን በአእምሮ መያዝ" },
  { word: "impromptu", pos: "adjective", ipa: "/ɪmˈprɒmp.tjuː/", syllables: ["im","promp","tu"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Done without preparation; spontaneous." }],
    examples: ["She gave an impromptu performance.", "We had an impromptu picnic."],
    synonyms: ["spontaneous", "improvised", "unplanned"], antonyms: ["planned", "rehearsed"],
    amharic: "ያልተዘጋጀ; ድንገተኛ; ያለ ዝግጅት የተደረገ" },
  { word: "juxtapose", pos: "verb", ipa: "/ˌdʒʌk.stəˈpəʊz/", syllables: ["jux","ta","pose"], cefr: "C2",
    definitions: [{ pos: "verb", text: "To place close together for contrast." }],
    examples: ["The artist juxtaposes old and new.", "Juxtaposing the photos reveals changes."],
    synonyms: ["contrast", "compare"], antonyms: ["separate"],
    amharic: "አጠገብ አድርጎ ማነጻጸር; ለማነጻጸር አብሮ ማስቀመጥ" },
  { word: "kindred", pos: "adjective", ipa: "/ˈkɪn.drəd/", syllables: ["kin","dred"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Similar in character; related." }],
    examples: ["They are kindred spirits.", "She found kindred topics in literature." ],
    synonyms: ["related", "akin", "similar"], antonyms: ["unrelated"],
    amharic: "ተመሳሳይ; ዝምድና ያለው; ተመሳሳይ ባህሪ ያለው" },
  { word: "latent", pos: "adjective", ipa: "/ˈleɪ.tənt/", syllables: ["la","tent"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Present but not yet visible or active." }],
    examples: ["She has latent talent as a singer.", "The virus can remain latent for years."],
    synonyms: ["dormant", "hidden", "potential"], antonyms: ["active", "manifest"],
    amharic: "ድብቅ; እስካሁን ያልታየ ግን ያለ" },
  { word: "mercurial", pos: "adjective", ipa: "/mɜːˈkjʊə.ri.əl/", syllables: ["mer","cu","ri","al"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Subject to sudden mood changes; lively." }],
    examples: ["Her mercurial temper kept us on edge.", "A mercurial mind jumps quickly."],
    synonyms: ["volatile", "unpredictable"], antonyms: ["steady", "consistent"],
    amharic: "ስሜቱ በፍጥነት የሚለዋወጥ; ንቁ" },
  { word: "novice", pos: "noun", ipa: "/ˈnɒv.ɪs/", syllables: ["nov","ice"], cefr: "B2",
    definitions: [{ pos: "noun", text: "A person new to a field; beginner." }],
    examples: ["She is a novice at chess.", "The course is designed for novices."],
    synonyms: ["beginner", "newcomer", "amateur"], antonyms: ["expert", "veteran"],
    amharic: "ጀማሪ; ልምድ የሌለው ሰው" },
  { word: "ostracize", pos: "verb", ipa: "/ˈɒs.trə.saɪz/", syllables: ["os","tra","cize"], cefr: "C2",
    definitions: [{ pos: "verb", text: "To exclude from a society or group." }],
    examples: ["She was ostracized for her views.", "The clique ostracized the new student."],
    synonyms: ["exclude", "shun", "boycott"], antonyms: ["include", "welcome"],
    amharic: "ማግለል; ከማህበር ማስወጣት" },
  { word: "peruse", pos: "verb", ipa: "/pəˈruːz/", syllables: ["pe","ruse"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To read through with thoroughness or care." }],
    examples: ["She perused the menu carefully.", "He perused the contract line by line."],
    synonyms: ["examine", "browse", "scan"], antonyms: ["skim"],
    amharic: "በጥንቃቄ ማንበብ; በዝርዝር መመርመር" },
  { word: "quandary", pos: "noun", ipa: "/ˈkwɒn.dri/", syllables: ["quan","dry"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A state of uncertainty over what to do." }],
    examples: ["I'm in a quandary about which job to take.", "The sudden question left him in a quandary."],
    synonyms: ["dilemma", "predicament"], antonyms: ["clarity"],
    amharic: "ግራ መጋባት; ምን ማድረግ እንዳለበት እርግጠኛ አለመሆን" },
  { word: "reverie", pos: "noun", ipa: "/ˈrev.ər.i/", syllables: ["rev","e","rie"], cefr: "C1",
    definitions: [{ pos: "noun", text: "A state of being lost in thought; daydream." }],
    examples: ["She fell into a reverie.", "The music broke his reverie."],
    synonyms: ["daydream", "fantasy", "musing"], antonyms: ["reality"],
    amharic: "ሕልም አለም; በሀሳብ ውስጥ መጥመቅ" },
  { word: "stoic", pos: "adjective", ipa: "/ˈstəʊ.ɪk/", syllables: ["sto","ic"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Enduring pain without showing emotion." }],
    examples: ["He remained stoic during the trial.", "A stoic acceptance of fate."],
    synonyms: ["resigned", "unemotional", "patient"], antonyms: ["emotional"],
    amharic: "ታጋሽ; ህመምን ያለ ቅሬታ የሚታገስ" },
  { word: "trepidation", pos: "noun", ipa: "/ˌtrep.ɪˈdeɪ.ʃən/", syllables: ["trep","i","da","tion"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A feeling of fear about something that may happen." }],
    examples: ["She opened the letter with trepidation.", "He faced the interview with some trepidation."],
    synonyms: ["apprehension", "fear", "anxiety"], antonyms: ["confidence"],
    amharic: "ፍርሃት; ስጋት; ስለሚሆነው ነገር መጨነቅ" },
  { word: "upheaval", pos: "noun", ipa: "/ʌpˈhiː.vəl/", syllables: ["up","heav","al"], cefr: "C1",
    definitions: [{ pos: "noun", text: "A violent or sudden change; disruption." }],
    examples: ["The country went through political upheaval.", "Moving house caused a major upheaval."],
    synonyms: ["turmoil", "upheaval", "disruption"], antonyms: ["stability"],
    amharic: "ለውጥ; መረበሽ; ድንገተኛ ብጥብጥ" },
  { word: "vehement", pos: "adjective", ipa: "/ˈviː.ə.mənt/", syllables: ["ve","he","ment"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Showing strong feeling; forceful." }],
    examples: ["She was vehement in her denial.", "A vehement protest shook the city."],
    synonyms: ["forceful", "passionate", "fervent"], antonyms: ["mild", "tepid"],
    amharic: "ጠንካራ ስሜት ያለው; ሃይለኛ" },
  { word: "wistful", pos: "adjective", ipa: "/ˈwɪst.fəl/", syllables: ["wist","ful"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Having a feeling of vague or regretful longing." }],
    examples: ["She gave a wistful sigh.", "A wistful smile crossed his face."],
    synonyms: ["yearning", "melancholy", "pensive"], antonyms: ["content"],
    amharic: "ናፋቂ; ሀዘን የቀላቀለ ናፍቆት" },
  { word: "yearn", pos: "verb", ipa: "/jɜːn/", syllables: ["yearn"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To have an intense feeling of longing." }],
    examples: ["She yearned for home.", "He yearns to travel the world."],
    synonyms: ["long", "desire", "crave"], antonyms: ["despise"],
    amharic: "መናፈቅ; በጣም መመኘት; ከፍተኛ ፍላጎት ማድረግ" },
  { word: "zeal", pos: "noun", ipa: "/ziːl/", syllables: ["zeal"], cefr: "C1",
    definitions: [{ pos: "noun", text: "Great energy or enthusiasm." }],
    examples: ["She approached her work with zeal.", "Religious zeal can be dangerous."],
    synonyms: ["passion", "fervor", "enthusiasm"], antonyms: ["apathy"],
    amharic: "ቅንዓት; ከፍተኛ ጉጉት; ጥረት" },
  { word: "abate", pos: "verb", ipa: "/əˈbeɪt/", syllables: ["a","bate"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To become less strong; to diminish." }],
    examples: ["The storm will abate by morning.", "His excitement abated as the days passed."],
    synonyms: ["subside", "decrease", "wane"], antonyms: ["intensify", "increase"],
    amharic: "መቀነስ; መዳከም; ማሽቆልቆል" },
  { word: "candidly", pos: "adverb", ipa: "/ˈkæn.dɪd.li/", syllables: ["can","did","ly"], cefr: "C1",
    definitions: [{ pos: "adv", text: "In a frank and honest manner." }],
    examples: ["She spoke candidly about her past.", "He answered candidly."],
    synonyms: ["frankly", "honestly"], antonyms: ["evasively"],
    amharic: "በሐቀኝነት; በግልጽ; ያለ ማመነታት" },
  { word: "dwindle", pos: "verb", ipa: "/ˈdwɪn.dəl/", syllables: ["dwin","dle"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To diminish gradually in size or amount." }],
    examples: ["Supplies dwindled as winter approached.", "His savings dwindled away."],
    synonyms: ["shrink", "decrease", "decline"], antonyms: ["grow", "increase"],
    amharic: "ቀስ በቀስ መቀነስ; መሟጠጥ" },
  { word: "ephemeral", pos: "adjective", ipa: "/ɪˈfem.ər.əl/", syllables: ["e","phem","er","al"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Lasting for a very short time." }],
    examples: ["Fame can be ephemeral.", "Beauty of cherry blossoms is ephemeral."],
    synonyms: ["fleeting", "transient", "brief"], antonyms: ["lasting", "eternal"],
    amharic: "ጊዜያዊ; ለአጭር ጊዜ የሚቆይ; ዘላቂ ያልሆነ" },
  { word: "fortuitous", pos: "adjective", ipa: "/fɔːˈtjuː.ɪ.təs/", syllables: ["for","tu","i","tous"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Happening by chance, often fortunately." }],
    examples: ["Their meeting was fortuitous.", "A fortuitous discovery changed her career."],
    synonyms: ["chance", "lucky", "serendipitous"], antonyms: ["planned"],
    amharic: "አጋጣሚ; እንደ አጋጣሚ የሆነ" },
]

// ---------- IELTS academic words ----------
const IELTS: SeedWord[] = [
  { word: "accelerate", pos: "verb", ipa: "/əkˈsel.ər.eɪt/", syllables: ["ac","cel","er","ate"], cefr: "B2",
    definitions: [{ pos: "verb", text: "To begin to move faster; to speed up." }],
    examples: ["The car accelerated to overtake the bus.", "Inflation has accelerated sharply."],
    synonyms: ["speed up", "quicken"], antonyms: ["decelerate"],
    amharic: "ማፋጠን; ፍጥነትን መጨመር" },
  { word: "accumulation", pos: "noun", ipa: "/əˌkjuː.mjəˈleɪ.ʃən/", syllables: ["ac","cu","mu","la","tion"], cefr: "C1",
    definitions: [{ pos: "noun", text: "The gathering or amassing of things over time." }],
    examples: ["An accumulation of dust covered the books.", "The accumulation of wealth was his goal."],
    synonyms: ["collection", "amassing"], antonyms: ["dispersal"],
    amharic: "ክምችት; በጊዜ ሂደት መከማቸት" },
  { word: "advocate", pos: "verb", ipa: "/ˈæd.və.keɪt/", syllables: ["ad","vo","cate"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To publicly recommend or support." }],
    examples: ["She advocates for children's rights.", "They advocate a balanced diet."],
    synonyms: ["support", "endorse", "champion"], antonyms: ["oppose"],
    amharic: "መደገፍ; በይፋ መደገፍ; ማስተዋወቅ" },
  { word: "arbitrary", pos: "adjective", ipa: "/ˈɑː.bɪ.trə.ri/", syllables: ["ar","bi","tra","ry"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Based on random choice rather than reason." }],
    examples: ["The decision seemed arbitrary.", "An arbitrary rule annoyed the staff."],
    synonyms: ["random", "capricious"], antonyms: ["reasoned"],
    amharic: "የዘፈቀደ; ያለ ምክንያት የተመረጠ" },
  { word: "aspiration", pos: "noun", ipa: "/ˌæs.pəˈreɪ.ʃən/", syllables: ["as","pi","ra","tion"], cefr: "C1",
    definitions: [{ pos: "noun", text: "A strong hope or ambition." }],
    examples: ["Her aspiration is to become a doctor.", "Young people have many aspirations."],
    synonyms: ["ambition", "dream"], antonyms: [],
    amharic: "ምኞት; ትልቅ ህልም ወይም ከፍተኛ ፍላጎት" },
  { word: "coherent", pos: "adjective", ipa: "/kəʊˈhɪə.rənt/", syllables: ["co","her","ent"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Logical and consistent." }],
    examples: ["She presented a coherent argument.", "His essay was clear and coherent."],
    synonyms: ["logical", "consistent"], antonyms: ["incoherent"],
    amharic: "ወጥ; አመክንዮአዊ; የተጣጣመ" },
  { word: "comprehensive", pos: "adjective", ipa: "/ˌkɒm.prɪˈhen.sɪv/", syllables: ["com","pre","hen","sive"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Complete; covering all aspects." }],
    examples: ["The report gives a comprehensive overview.", "A comprehensive insurance policy."],
    synonyms: ["thorough", "complete"], antonyms: ["partial"],
    amharic: "ሁሉን አቀፍ; የተሟላ; ሁሉንም ገጽታ የሚሸፍን" },
  { word: "consequence", pos: "noun", ipa: "/ˈkɒn.sɪ.kwəns/", syllables: ["con","se","quence"], cefr: "B2",
    definitions: [{ pos: "noun", text: "A result or effect of an action." }],
    examples: ["He must face the consequences of his acts.", "The consequences were severe."],
    synonyms: ["result", "outcome"], antonyms: ["cause"],
    amharic: "ውጤት; መዘዝ; የአንድ ድርጊት ውጥን" },
  { word: "controversial", pos: "adjective", ipa: "/ˌkɒn.trəˈvɜː.ʃəl/", syllables: ["con","tro","ver","sial"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Giving rise to public disagreement." }],
    examples: ["The topic is highly controversial.", "A controversial new law was passed."],
    synonyms: ["debatable", "disputed"], antonyms: ["undisputed"],
    amharic: "አወዛጋቢ; ሰዎች የሚለያዩበት" },
  { word: "criteria", pos: "noun", ipa: "/kraɪˈtɪə.ri.ə/", syllables: ["cri","te","ri","a"], cefr: "C1",
    definitions: [{ pos: "noun", text: "Principles or standards for judging." }],
    examples: ["What criteria do you use to select candidates?", "The criteria are clearly stated."],
    synonyms: ["standards", "principles"], antonyms: [],
    amharic: "መስፈርት; ለመዳኘት የሚያገለግሉ ደረጃዎች" },
  { word: "demonstrate", pos: "verb", ipa: "/ˈdem.ən.streɪt/", syllables: ["dem","on","strate"], cefr: "B2",
    definitions: [{ pos: "verb", text: "To clearly show or prove." }],
    examples: ["The experiment demonstrates the theory.", "She demonstrated how the device works."],
    synonyms: ["show", "prove", "illustrate"], antonyms: [],
    amharic: "ማሳየት; ማረጋገጥ; በግልጽ ማሳየት" },
  { word: "discrepancy", pos: "noun", ipa: "/dɪˈskrep.ən.si/", syllables: ["dis","crep","an","cy"], cefr: "C1",
    definitions: [{ pos: "noun", text: "A difference between things that should match." }],
    examples: ["There is a discrepancy in the figures.", "A discrepancy between theory and practice."],
    synonyms: ["difference", "inconsistency"], antonyms: ["agreement"],
    amharic: "ልዩነት; አለመመሳሰል; አለመጣጣም" },
  { word: "diverse", pos: "adjective", ipa: "/daɪˈvɜːs/", syllables: ["di","verse"], cefr: "B2",
    definitions: [{ pos: "adj", text: "Showing a great deal of variety." }],
    examples: ["The city has a diverse population.", "Diverse opinions were heard."],
    synonyms: ["varied", "various"], antonyms: ["uniform"],
    amharic: "የተለያየ; ልዩ ልዩ; የተፈራረቀ" },
  { word: "dominant", pos: "adjective", ipa: "/ˈdɒm.ɪ.nənt/", syllables: ["dom","i","nant"], cefr: "C1",
    definitions: [{ pos: "adj", text: "Most important or powerful." }],
    examples: ["The dominant culture shapes society.", "He has a dominant personality."],
    synonyms: ["prevalent", "leading"], antonyms: ["subordinate"],
    amharic: "ዋና; ተወዳዳሪ የሌለው; ኃያል" },
  { word: "emphasize", pos: "verb", ipa: "/ˈem.fə.saɪz/", syllables: ["em","pha","size"], cefr: "B2",
    definitions: [{ pos: "verb", text: "To give special importance to." }],
    examples: ["She emphasized the need for teamwork.", "He emphasized each word carefully."],
    synonyms: ["stress", "highlight"], antonyms: ["downplay"],
    amharic: "ማጉላት; አጽንኦት መስጠት; ልዩ ትኩረት መስጠት" },
  { word: "evaluate", pos: "verb", ipa: "/ɪˈvæl.ju.eɪt/", syllables: ["e","val","u","ate"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To form an idea of the value of; assess." }],
    examples: ["We need to evaluate the results.", "She was evaluated on her performance."],
    synonyms: ["assess", "appraise"], antonyms: [],
    amharic: "መገምገም; ዋጋን ወይም ደረጃን መወሰን" },
  { word: "fluctuate", pos: "verb", ipa: "/ˈflʌk.tʃu.eɪt/", syllables: ["fluc","tu","ate"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To rise and fall irregularly." }],
    examples: ["Prices fluctuate throughout the year.", "His mood fluctuates a lot."],
    synonyms: ["vary", "oscillate"], antonyms: ["stabilize"],
    amharic: "መለዋወጥ; ወደላይ ወደታች መለዋወጥ" },
  { word: "fundamental", pos: "adjective", ipa: "/ˌfʌn.dəˈmen.təl/", syllables: ["fun","da","men","tal"], cefr: "B2",
    definitions: [{ pos: "adj", text: "Forming a necessary base or core." }],
    examples: ["Honesty is a fundamental value.", "There is a fundamental difference."],
    synonyms: ["basic", "essential"], antonyms: ["peripheral"],
    amharic: "መሠረታዊ; ዋና; አስፈላጊ" },
  { word: "generate", pos: "verb", ipa: "/ˈdʒen.ər.eɪt/", syllables: ["gen","er","ate"], cefr: "B2",
    definitions: [{ pos: "verb", text: "To produce or create." }],
    examples: ["The plant generates electricity.", "His speech generated excitement."],
    synonyms: ["produce", "create"], antonyms: ["destroy"],
    amharic: "ማመንጨት; መፍጠር; ማምረት" },
  { word: "hypothesis", pos: "noun", ipa: "/haɪˈpɒθ.ə.sɪs/", syllables: ["hy","poth","e","sis"], cefr: "C1",
    definitions: [{ pos: "noun", text: "A proposed explanation for a phenomenon." }],
    examples: ["The hypothesis was tested in the lab.", "She proposed a new hypothesis."],
    synonyms: ["theory", "premise"], antonyms: [],
    amharic: "መላምት; ለአንድ ክስተት የቀረበ ማብራሪያ" },
  { word: "implement", pos: "verb", ipa: "/ˈɪm.plɪ.ment/", syllables: ["im","ple","ment"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To put a plan into effect." }],
    examples: ["We will implement the new policy.", "The system was implemented last month."],
    synonyms: ["execute", "apply"], antonyms: [],
    amharic: "መተግበር; ወደ ተግባር ማዋል; ማስፈጸም" },
  { word: "incentive", pos: "noun", ipa: "/ɪnˈsen.tɪv/", syllables: ["in","cen","tive"], cefr: "C1",
    definitions: [{ pos: "noun", text: "Something that motivates action." }],
    examples: ["Bonuses are an incentive for workers.", "Tax incentives attract investors."],
    synonyms: ["motivation", "stimulus"], antonyms: ["disincentive"],
    amharic: "ማበረታቻ; ድርጊትን የሚቀሰቅስ ነገር" },
  { word: "integrate", pos: "verb", ipa: "/ˈɪn.tɪ.ɡreɪt/", syllables: ["in","te","grate"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To combine parts into a whole." }],
    examples: ["We must integrate the new system.", "She integrated smoothly into the team."],
    synonyms: ["combine", "merge"], antonyms: ["separate"],
    amharic: "ማዋሃድ; አንድ ማድረግ; መቀላቀል" },
  { word: "justify", pos: "verb", ipa: "/ˈdʒʌs.tɪ.faɪ/", syllables: ["jus","ti","fy"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To show to be right or reasonable." }],
    examples: ["He tried to justify his actions.", "Can you justify the cost?"],
    synonyms: ["defend", "explain"], antonyms: ["condemn"],
    amharic: "ማስረዳት; ትክክል መሆኑን ማረጋገጥ" },
  { word: "longevity", pos: "noun", ipa: "/lɒnˈdʒev.ə.ti/", syllables: ["lon","gev","i","ty"], cefr: "C1",
    definitions: [{ pos: "noun", text: "Long life or duration." }],
    examples: ["Diet affects longevity.", "The longevity of the battery is impressive."],
    synonyms: ["long life", "durability"], antonyms: [],
    amharic: "ረጅም ዕድሜ; የረጅም ጊዜ ዘላቂነት" },
  { word: "manipulate", pos: "verb", ipa: "/məˈnɪp.jə.leɪt/", syllables: ["ma","nip","u","late"], cefr: "C1",
    definitions: [{ pos: "verb", text: "To control or influence cleverly." }],
    examples: ["He tried to manipulate the situation.", "She manipulated the data to fit her theory."],
    synonyms: ["control", "influence"], antonyms: [],
    amharic: "መቆጣጠር; በብልሃት ተጽዕኖ ማድረግ" },
  { word: "negotiate", pos: "verb", ipa: "/nɪˈɡəʊ.ʃi.eɪt/", syllables: ["ne","go","ti","ate"], cefr: "B2",
    definitions: [{ pos: "verb", text: "To discuss to reach an agreement." }],
    examples: ["They negotiated a peace treaty.", "She negotiated a better salary."],
    synonyms: ["bargain", "discuss"], antonyms: [],
    amharic: "መደራደር; ስምምነት ላይ ለመድረስ መወያየት" },
]

// ---------- TOEFL academic words ----------
const TOEFL: SeedWord[] = [
  { word: "abstraction", pos: "noun", ipa: "/æbˈstræk.ʃən/", syllables: ["ab","strac","tion"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A general idea not tied to a concrete instance." }],
    examples: ["Love and justice are abstractions.", "The painting shows pure abstraction."],
    synonyms: ["concept", "idea"], antonyms: ["concrete"],
    amharic: "ረቂቅ ሀሳብ; ከተጨባጭ ነገር የራቀ አስተሳሰብ" },
  { word: "anomaly", pos: "noun", ipa: "/əˈnɒm.ə.li/", syllables: ["a","nom","a","ly"], cefr: "C2",
    definitions: [{ pos: "noun", text: "Something that deviates from what is normal." }],
    examples: ["The warm winter is a climate anomaly.", "Scientists noticed an anomaly in the data."],
    synonyms: ["irregularity", "abnormality"], antonyms: ["norm"],
    amharic: "ያልተለመደ ነገር; ከመደበኛ የተለየ" },
  { word: "antiquated", pos: "adjective", ipa: "/ˈæn.tɪ.kweɪ.tɪd/", syllables: ["an","ti","quated"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Old-fashioned or outdated." }],
    examples: ["The factory uses antiquated machinery.", "Their laws are antiquated."],
    synonyms: ["outdated", "obsolete"], antonyms: ["modern"],
    amharic: "ጊዜ ያለፈበት; ያረጀ; ፋሽን ያልሆነ" },
  { word: "coalesce", pos: "verb", ipa: "/ˌkəʊ.əˈles/", syllables: ["co","a","lesce"], cefr: "C2",
    definitions: [{ pos: "verb", text: "To come together to form one whole." }],
    examples: ["Various groups coalesced into a single party.", "The drops coalesced into a puddle."],
    synonyms: ["merge", "unite"], antonyms: ["split"],
    amharic: "መቀላቀል; አንድ ላይ ተሰባስቦ አንድ መሆን" },
  { word: "conundrum", pos: "noun", ipa: "/kəˈnʌn.drəm/", syllables: ["co","nun","drum"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A confusing and difficult problem or question." }],
    examples: ["The puzzle is a real conundrum.", "How to fund the project remains a conundrum."],
    synonyms: ["puzzle", "riddle"], antonyms: [],
    amharic: "አጣብቂኝ ጥያቄ; ለመረዳት የሚከብድ ችግር" },
  { word: "derivative", pos: "adjective", ipa: "/dɪˈrɪv.ə.tɪv/", syllables: ["de","riv","a","tive"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Imitative of another's work; unoriginal." }],
    examples: ["The film feels derivative of older classics.", "A derivative style of painting."],
    synonyms: ["unoriginal", "imitative"], antonyms: ["original"],
    amharic: "የተቀዳ; ከሌላ ሰው ስራ የተወሰደ; ኦሪጅናል ያልሆነ" },
  { word: "dichotomy", pos: "noun", ipa: "/daɪˈkɒt.ə.mi/", syllables: ["di","chot","o","my"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A division into two opposing parts." }],
    examples: ["There is a dichotomy between theory and practice.", "The dichotomy of mind and body."],
    synonyms: ["division", "split"], antonyms: [],
    amharic: "ሁለት ተቃራኒ ክፍሎች መከፋፈል" },
  { word: "didactic", pos: "adjective", ipa: "/daɪˈdæk.tɪk/", syllables: ["di","dac","tic"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Intended to teach, often morally." }],
    examples: ["The novel has a didactic tone.", "A didactic approach can bore children."],
    synonyms: ["instructive", "moralistic"], antonyms: [],
    amharic: "አስተማሪ; ሥነ ምግባርን ለማስተማር የታሰበ" },
  { word: "dogmatic", pos: "adjective", ipa: "/dɒɡˈmæt.ɪk/", syllables: ["dog","mat","ic"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Stating opinions as if they were facts." }],
    examples: ["His dogmatic views annoyed colleagues.", "A dogmatic approach leaves no room for debate."],
    synonyms: ["rigid", "opinionated"], antonyms: ["flexible"],
    amharic: "ርዕዮተ ጽኑ; የራሱን አስተያየት እንደ እውነት የሚያቀርብ" },
  { word: "eclectic", pos: "adjective", ipa: "/ɪˈklek.tɪk/", syllables: ["ec","lec","tic"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Derived from various sources." }],
    examples: ["She has an eclectic taste in music.", "An eclectic collection of furniture."],
    synonyms: ["diverse", "varied"], antonyms: ["narrow"],
    amharic: "ከተለያዩ ምንጮች የተወሰደ; ልዩ ልዩ" },
  { word: "ephemera", pos: "noun", ipa: "/ɪˈfem.ər.ə/", syllables: ["e","phem","er","a"], cefr: "C2",
    definitions: [{ pos: "noun", text: "Things that are short-lived." }],
    examples: ["The museum keeps paper ephemera.", "Social media posts are digital ephemera."],
    synonyms: ["transient items"], antonyms: [],
    amharic: "ለአጭር ጊዜ የሚቆዩ ነገሮች" },
  { word: "fallacy", pos: "noun", ipa: "/ˈfæl.ə.si/", syllables: ["fal","la","cy"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A mistaken belief based on faulty reasoning." }],
    examples: ["The argument rests on a fallacy.", "It's a fallacy that money brings happiness."],
    synonyms: ["misconception", "error"], antonyms: [],
    amharic: "የተሳሳተ እምነት; የተሳሳተ አመለካከት" },
  { word: "fervent", pos: "adjective", ipa: "/ˈfɜː.vənt/", syllables: ["fer","vent"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Showing intense feeling; passionate." }],
    examples: ["She is a fervent believer in justice.", "His fervent speech moved the audience."],
    synonyms: ["passionate", "ardent"], antonyms: ["tepid"],
    amharic: "ከፍተኛ ስሜት ያለው; ታዳጊ; ሃይለኛ" },
  { word: "grandiose", pos: "adjective", ipa: "/ˈɡræn.di.əʊs/", syllables: ["gran","di","ose"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Pretentiously grand or ambitious." }],
    examples: ["He has grandiose plans for the company.", "A grandiose building dominated the square."],
    synonyms: ["ostentatious", "pompous"], antonyms: ["modest"],
    amharic: "ግርማ የሞላበት; ከልክ ያለፈ ታላቅ" },
  { word: "iconoclast", pos: "noun", ipa: "/aɪˈkɒn.ə.klæst/", syllables: ["i","con","o","clast"], cefr: "C2",
    definitions: [{ pos: "noun", text: "One who attacks cherished beliefs." }],
    examples: ["He was an iconoclast in the art world.", "Iconoclasts challenge the status quo."],
    synonyms: ["dissenter", "rebel"], antonyms: [],
    amharic: "የተቀበሉ እምነቶችን የሚቃወም ሰው" },
  { word: "idiosyncrasy", pos: "noun", ipa: "/ˌɪd.i.əˈsɪŋ.krə.si/", syllables: ["id","i","o","syn","cra","sy"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A peculiar habit or characteristic." }],
    examples: ["One of her idiosyncrasies is humming while working.", "Each language has its idiosyncrasies."],
    synonyms: ["quirk", "peculiarity"], antonyms: [],
    amharic: "ልዩ ባህሪ ወይም ልማድ; የግል ልማድ" },
  { word: "impecunious", pos: "adjective", ipa: "/ˌɪm.peˈkjuː.ni.əs/", syllables: ["im","pe","cu","ni","ous"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Having little or no money." }],
    examples: ["An impecunious student lived on noodles.", "The impecunious poet could not pay rent."],
    synonyms: ["poor", "penniless"], antonyms: ["wealthy"],
    amharic: "ድሃ; ገንዘብ የሌለው; በጣም የተቸገረ" },
  { word: "incumbent", pos: "adjective", ipa: "/ɪnˈkʌm.bənt/", syllables: ["in","cum","bent"], cefr: "C2",
    definitions: [
      { pos: "adj", text: "Necessary for a particular role." },
      { pos: "noun", text: "The current holder of an office." }
    ],
    examples: ["It is incumbent on leaders to act ethically.", "The incumbent won re-election."],
    synonyms: ["obligatory", "current"], antonyms: [],
    amharic: "ግዴታ; አሁን ያለ የስልጣን ባለቤት" },
  { word: "jingoism", pos: "noun", ipa: "/ˈdʒɪŋ.ɡəʊ.ɪ.zəm/", syllables: ["jin","go","ism"], cefr: "C2",
    definitions: [{ pos: "noun", text: "Extreme patriotism, often aggressive." }],
    examples: ["The speech was full of jingoism.", "Jingoism can lead to conflict."],
    synonyms: ["chauvinism", "nationalism"], antonyms: [],
    amharic: "ጽንፈኛ አርበኝነት; ወራሪ ሀገር ወዳድነት" },
  { word: "litany", pos: "noun", ipa: "/ˈlɪt.ə.ni/", syllables: ["lit","a","ny"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A tedious recital or repetitive list." }],
    examples: ["He recited a litany of complaints.", "A litany of failures plagued the project."],
    synonyms: ["list", "recital"], antonyms: [],
    amharic: "ረጅም ዝርዝር ቅሬታ; ደጋጋሚ ዝርዝር" },
  { word: "machination", pos: "noun", ipa: "/ˌmæk.ɪˈneɪ.ʃən/", syllables: ["mach","i","na","tion"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A plot or scheme, typically evil." }],
    examples: ["The villain's machinations were uncovered.", "Political machinations continued behind the scenes."],
    synonyms: ["scheme", "plot"], antonyms: [],
    amharic: "ሴራ; ክፉ ዓላማ ያለው ዕቅድ" },
  { word: "nadir", pos: "noun", ipa: "/ˈneɪ.dɪər/", syllables: ["na","dir"], cefr: "C2",
    definitions: [{ pos: "noun", text: "The lowest point; opposite of zenith." }],
    examples: ["Stocks hit their nadir in March.", "His career reached its nadir that year."],
    synonyms: ["bottom", "low point"], antonyms: ["zenith", "peak"],
    amharic: "ዝቅተኛ ደረጃ; ዝቅተኛ ነጥብ" },
  { word: "overt", pos: "adjective", ipa: "/əʊˈvɜːt/", syllables: ["o","vert"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Done openly; not secret." }],
    examples: ["There was no overt hostility.", "An overt attempt to win votes."],
    synonyms: ["open", "obvious"], antonyms: ["covert"],
    amharic: "ግልጽ; በይፋ የተደረገ; ሚስጥራዊ ያልሆነ" },
  { word: "paradigm", pos: "noun", ipa: "/ˈpær.ə.daɪm/", syllables: ["par","a","digm"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A typical model or pattern." }],
    examples: ["The discovery shifted the scientific paradigm.", "A new paradigm of education."],
    synonyms: ["model", "pattern"], antonyms: [],
    amharic: "ምሳሌ; አብነት; የተለመደ ዘይቤ" },
  { word: "quagmire", pos: "noun", ipa: "/ˈkwæɡ.maɪər/", syllables: ["quag","mire"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A difficult situation; a muddy bog." }],
    examples: ["The war became a quagmire.", "The project turned into a financial quagmire."],
    synonyms: ["morass", "predicament"], antonyms: [],
    amharic: "ጭቃማ ቦታ; ከባድ ችግር ውስጥ መጥመቅ" },
  { word: "recalcitrant", pos: "adjective", ipa: "/rɪˈkæl.sɪ.trənt/", syllables: ["re","cal","ci","trant"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Having a defiant attitude to authority." }],
    examples: ["The recalcitrant child refused to obey.", "A recalcitrant witness blocked the inquiry."],
    synonyms: ["defiant", "stubborn"], antonyms: ["obedient"],
    amharic: "እንግዳ ተቃዋሚ; ስልጣንን የሚቃወም" },
  { word: "sycophant", pos: "noun", ipa: "/ˈsɪk.ə.fænt/", syllables: ["syc","o","phant"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A person who flatters to gain advantage." }],
    examples: ["The king was surrounded by sycophants.", "She despised the sycophants at court."],
    synonyms: ["flatterer", "toady"], antonyms: [],
    amharic: "አሳሳች; ለጥቅም ሲል የሚያመሰግን ሰው" },
  { word: "taciturn", pos: "adjective", ipa: "/ˈtæs.ɪ.tɜːn/", syllables: ["tac","i","turn"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Saying little; quiet in manner." }],
    examples: ["He is taciturn at parties.", "A taciturn reply of 'yes' was all we got."],
    synonyms: ["reserved", "silent"], antonyms: ["talkative"],
    amharic: "አነጋገር የሌለው; ጸጥታሽ; ብዙ የማይናገር" },
  { word: "vacillate", pos: "verb", ipa: "/ˈvæs.ɪ.leɪt/", syllables: ["vac","il","late"], cefr: "C2",
    definitions: [{ pos: "verb", text: "To waver between different opinions or actions." }],
    examples: ["She vacillated for weeks before deciding.", "He vacillates under pressure."],
    synonyms: ["waver", "hesitate"], antonyms: ["decide"],
    amharic: "ማመነታት; በሁለት አማራጮች መካከል መዋዠቅ" },
]

// ---------- GRE advanced words ----------
const GRE: SeedWord[] = [
  { word: "abjure", pos: "verb", ipa: "/əbˈdʒʊər/", syllables: ["ab","jure"], cefr: "C2",
    definitions: [{ pos: "verb", text: "To solemnly renounce; to give up." }],
    examples: ["He abjured his former beliefs.", "She abjured the use of violence."],
    synonyms: ["renounce", "forswear"], antonyms: ["embrace"],
    amharic: "በይፋ መተው; መካድ; መርቆ መተው" },
  { word: "abrogate", pos: "verb", ipa: "/ˈæb.rə.ɡeɪt/", syllables: ["ab","ro","gate"], cefr: "C2",
    definitions: [{ pos: "verb", text: "To repeal or revoke formally." }],
    examples: ["The treaty was abrogated by the new government.", "They abrogated their responsibility."],
    synonyms: ["repeal", "annul"], antonyms: ["enact"],
    amharic: "ሥርዓትን ማፍረስ; በሕጋዊ መንገድ መሻር" },
  { word: "acrimony", pos: "noun", ipa: "/ˈæk.rɪ.mə.ni/", syllables: ["ac","ri","mo","ny"], cefr: "C2",
    definitions: [{ pos: "noun", text: "Bitterness in speech or behavior." }],
    examples: ["The divorce was settled without acrimony.", "A debate full of acrimony."],
    synonyms: ["bitterness", "rancor"], antonyms: ["amity"],
    amharic: "መርጋት; በንግግር ወይም በባህሪ ላይ የሚታይ ቁጣ" },
  { word: "alacrity", pos: "noun", ipa: "/əˈlæk.rə.ti/", syllables: ["a","lac","ri","ty"], cefr: "C2",
    definitions: [{ pos: "noun", text: "Brisk cheerful readiness." }],
    examples: ["She accepted the invitation with alacrity.", "He set to work with alacrity."],
    synonyms: ["eagerness", "readiness"], antonyms: ["reluctance"],
    amharic: "በደስታ መቀበል; ፈጣን ፍቃደኝነት" },
  { word: "anomalous", pos: "adjective", ipa: "/əˈnɒm.ə.ləs/", syllables: ["a","nom","a","lous"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Deviating from the normal; irregular." }],
    examples: ["An anomalous reading puzzled the scientists.", "Her behavior was anomalous."],
    synonyms: ["irregular", "abnormal"], antonyms: ["normal"],
    amharic: "ያልተለመደ; ከተለመደው የተለየ" },
  { word: "aplomb", pos: "noun", ipa: "/əˈplɒm/", syllables: ["a","plomb"], cefr: "C2",
    definitions: [{ pos: "noun", text: "Self-confidence in demanding situations." }],
    examples: ["She handled the crisis with aplomb.", "He spoke with great aplomb."],
    synonyms: ["poise", "composure"], antonyms: ["nervousness"],
    amharic: "በአስቸጋሪ ሁኔታ ውስጥ መረጋጋት; በራስ መተማመን" },
  { word: "approbation", pos: "noun", ipa: "/ˌæp.rəˈbeɪ.ʃən/", syllables: ["ap","pro","ba","tion"], cefr: "C2",
    definitions: [{ pos: "noun", text: "Approval or praise." }],
    examples: ["The book received general approbation.", "He won the approbation of his peers."],
    synonyms: ["approval", "praise"], antonyms: ["disapproval"],
    amharic: "ማጽደቅ; ምስጋና; ይሁንታ" },
  { word: "ascetic", pos: "adjective", ipa: "/əˈset.ɪk/", syllables: ["as","cet","ic"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Practicing strict self-denial." }],
    examples: ["The monk lived an ascetic life.", "An ascetic diet of bread and water."],
    synonyms: ["austere", "severe"], antonyms: ["luxurious"],
    amharic: "ራስን የሚገድብ; ዝቅተኛ ኑሮ የሚመራ" },
  { word: "calumny", pos: "noun", ipa: "/ˈkæl.əm.ni/", syllables: ["cal","um","ny"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A false and malicious statement." }],
    examples: ["The article was full of calumny.", "She sued for calumny."],
    synonyms: ["slander", "libel"], antonyms: ["truth"],
    amharic: "ስም አጥፊ ወሬ; ሐሰተኛ ክስ" },
  { word: "candor", pos: "noun", ipa: "/ˈkæn.dər/", syllables: ["can","dor"], cefr: "C2",
    definitions: [{ pos: "noun", text: "The quality of being frank; honesty." }],
    examples: ["She spoke with great candor.", "His candor is refreshing."],
    synonyms: ["honesty", "frankness"], antonyms: ["deception"],
    amharic: "ሐቀኝነት; ግልጽነት; እውነተኝነት" },
  { word: "capricious", pos: "adjective", ipa: "/kəˈprɪʃ.əs/", syllables: ["ca","pri","cious"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Given to sudden changes of mood; impulsive." }],
    examples: ["The weather is capricious in spring.", "A capricious boss frustrates workers."],
    synonyms: ["fickle", "whimsical"], antonyms: ["steady"],
    amharic: "ስሜቱ በፍጥነት የሚለዋወጥ; ያልተረጋጋ" },
  { word: "chicanery", pos: "noun", ipa: "/ʃɪˈkeɪ.nər.i/", syllables: ["chi","can","er","y"], cefr: "C2",
    definitions: [{ pos: "noun", text: "The use of trickery to achieve a purpose." }],
    examples: ["The election was marred by chicanery.", "He exposed the company's financial chicanery."],
    synonyms: ["trickery", "deception"], antonyms: [],
    amharic: "ተንኮል; ማታለል; ዓላማን ለማሳካት ማጭበርበር" },
  { word: "churlish", pos: "adjective", ipa: "/ˈtʃɜː.lɪʃ/", syllables: ["chur","lish"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Rude in a mean-spirited way." }],
    examples: ["His churlish behavior spoiled the dinner.", "It would be churlish to refuse the gift."],
    synonyms: ["rude", "surly"], antonyms: ["polite"],
    amharic: "ሸካራ; ባለጌ; ጨዋነት የጎደለው" },
  { word: "cogent", pos: "adjective", ipa: "/ˈkəʊ.dʒənt/", syllables: ["co","gent"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Clear, logical, and convincing." }],
    examples: ["She gave a cogent argument.", "A cogent case for reform."],
    synonyms: ["convincing", "persuasive"], antonyms: ["weak"],
    amharic: "አሳማኝ; ግልጽ እና አመክንዮአዊ" },
  { word: "convoluted", pos: "adjective", ipa: "/ˈkɒn.və.luː.tɪd/", syllables: ["con","vo","lu","ted"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Extremely complex and hard to follow." }],
    examples: ["A convoluted plot", "His reasoning was convoluted."],
    synonyms: ["complex", "intricate"], antonyms: ["simple"],
    amharic: "የተወሳሰበ; ለመረዳት የሚከብድ" },
  { word: "decorum", pos: "noun", ipa: "/dɪˈkɔː.rəm/", syllables: ["de","co","rum"], cefr: "C2",
    definitions: [{ pos: "noun", text: "Behavior in keeping with good taste." }],
    examples: ["The ceremony was conducted with decorum.", "He maintained decorum throughout."],
    synonyms: ["propriety", "dignity"], antonyms: [],
    amharic: "ጨዋነት; ተገቢ ባህሪ; ሥርዓት" },
  { word: "desiccate", pos: "verb", ipa: "/ˈdes.ɪ.keɪt/", syllables: ["des","ic","cate"], cefr: "C2",
    definitions: [{ pos: "verb", text: "To dry out completely." }],
    examples: ["The sun desiccated the soil.", "Desiccated coconut is used in baking."],
    synonyms: ["dehydrate", "dry"], antonyms: ["moisten"],
    amharic: "ማድረቅ; ውሃውን ሙሉ በሙሉ ማስወገድ" },
  { word: "diatribe", pos: "noun", ipa: "/ˈdaɪ.ə.traɪb/", syllables: ["di","a","tribe"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A forceful and bitter verbal attack." }],
    examples: ["He launched into a diatribe against the press.", "Her diary is a diatribe on modern life."],
    synonyms: ["tirade", "harangue"], antonyms: [],
    amharic: "ኃይለኛ የቃል ጥቃት; ረጅም ነቀፋ" },
  { word: "disparage", pos: "verb", ipa: "/dɪˈspær.ɪdʒ/", syllables: ["dis","par","age"], cefr: "C2",
    definitions: [{ pos: "verb", text: "To belittle or speak slightingly of." }],
    examples: ["Don't disparage her efforts.", "He disparaged the proposal."],
    synonyms: ["belittle", "deprecate"], antonyms: ["praise"],
    amharic: "ማቃለል; ማዋረድ; አቅልሎ መናገር" },
  { word: "enervate", pos: "verb", ipa: "/ˈen.ər.veɪt/", syllables: ["en","er","vate"], cefr: "C2",
    definitions: [{ pos: "verb", text: "To cause to feel drained of energy." }],
    examples: ["The heat enervated the workers.", "A long speech enervated the audience."],
    synonyms: ["weaken", "exhaust"], antonyms: ["invigorate"],
    amharic: "ሃይል ማሳጣት; ደካማ ማድረግ" },
  { word: "esoteric", pos: "adjective", ipa: "/ˌes.əˈter.ɪk/", syllables: ["es","o","ter","ic"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Intended for a select few; obscure." }],
    examples: ["He has esoteric tastes in literature.", "An esoteric philosophical debate."],
    synonyms: ["obscure", "arcane"], antonyms: ["accessible"],
    amharic: "ለጥቂቶች ብቻ የታሰበ; ሚስጥራዊ ዕውቀት" },
  { word: "exacerbate", pos: "verb", ipa: "/ɪɡˈzæs.ər.beɪt/", syllables: ["ex","ac","er","bate"], cefr: "C2",
    definitions: [{ pos: "verb", text: "To make a bad situation worse." }],
    examples: ["His remarks exacerbated the tension.", "Stress can exacerbate health problems."],
    synonyms: ["worsen", "aggravate"], antonyms: ["alleviate"],
    amharic: "ማባባስ; የከፋ ማድረግ; ሁኔታን ማባባስ" },
  { word: "garrulous", pos: "adjective", ipa: "/ˈɡær.ə.ləs/", syllables: ["gar","ru","lous"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Excessively talkative." }],
    examples: ["The garrulous old man told endless stories.", "A garrulous friend never stops chatting."],
    synonyms: ["talkative", "loquacious"], antonyms: ["taciturn"],
    amharic: "በጣም ተናጋሪ; ያለማቋረጥ የሚያወራ" },
  { word: "ingenuous", pos: "adjective", ipa: "/ɪnˈdʒen.ju.əs/", syllables: ["in","gen","u","ous"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Innocent and unsuspecting." }],
    examples: ["Her ingenuous smile won everyone over.", "He was ingenuous enough to believe them."],
    synonyms: ["naive", "innocent"], antonyms: ["calculating"],
    amharic: "ንጹህ ልብ; ምንም ጥርጣሬ የሌለው" },
  { word: "obfuscate", pos: "verb", ipa: "/ˈɒb.fʌs.keɪt/", syllables: ["ob","fus","cate"], cefr: "C2",
    definitions: [{ pos: "verb", text: "To deliberately make unclear." }],
    examples: ["Politicians obfuscate the facts.", "The contract was obfuscated in legal jargon."],
    synonyms: ["confuse", "obscure"], antonyms: ["clarify"],
    amharic: "ሆን ብሎ ግራ ማጋባት; ግልጽ አለማድረግ" },
  { word: "pernicious", pos: "adjective", ipa: "/pəˈnɪʃ.əs/", syllables: ["per","ni","cious"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Having a harmful effect, especially gradually." }],
    examples: ["A pernicious rumor spread through the office.", "Pernicious weeds choked the crops."],
    synonyms: ["harmful", "destructive"], antonyms: ["beneficial"],
    amharic: "ጎጂ; ቀስ በቀስ የሚጎዳ" },
  { word: "plethora", pos: "noun", ipa: "/ˈpleθ.ər.ə/", syllables: ["pleth","o","ra"], cefr: "C2",
    definitions: [{ pos: "noun", text: "An excess of something." }],
    examples: ["A plethora of choices can overwhelm buyers.", "There is a plethora of apps for fitness."],
    synonyms: ["excess", "abundance"], antonyms: ["scarcity"],
    amharic: "ከፍተኛ ብዛት; ከመጠን በላይ" },
  { word: "predilection", pos: "noun", ipa: "/ˌpriː.dɪˈlek.ʃən/", syllables: ["pre","di","lec","tion"], cefr: "C2",
    definitions: [{ pos: "noun", text: "A preference or special liking." }],
    examples: ["She has a predilection for jazz.", "His predilection for sweets is well known."],
    synonyms: ["preference", "liking"], antonyms: ["aversion"],
    amharic: "ልዩ መውደድ; ዝንባሌ; የተለየ ፍላጎት" },
  { word: "recant", pos: "verb", ipa: "/rɪˈkænt/", syllables: ["re","cant"], cefr: "C2",
    definitions: [{ pos: "verb", text: "To formally renounce a belief." }],
    examples: ["He was forced to recant his views.", "She refused to recant."],
    synonyms: ["renounce", "retract"], antonyms: ["affirm"],
    amharic: "ከሃይማኖት ወይም እምነት መመለስ; መካድ" },
  { word: "salient", pos: "adjective", ipa: "/ˈseɪ.li.ənt/", syllables: ["sa","li","ent"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Most noticeable or important." }],
    examples: ["He summarized the salient points.", "The salient feature of the plan is its simplicity."],
    synonyms: ["prominent", "conspicuous"], antonyms: ["insignificant"],
    amharic: "ዋና; ታዋቂ; ትኩረት የሚስብ" },
  { word: "truculent", pos: "adjective", ipa: "/ˈtrʌk.jə.lənt/", syllables: ["truc","u","lent"], cefr: "C2",
    definitions: [{ pos: "adj", text: "Eager to fight; fiercely aggressive." }],
    examples: ["A truculent teenager challenged the teacher.", "His truculent tone scared the staff."],
    synonyms: ["aggressive", "belligerent"], antonyms: ["peaceful"],
    amharic: "ጠብ አጫሪ; ለውጊያ የሚጓጓ; ኃይለኛ" },
]

const DECKS = [
  { name: "Common 500 (B1-C2)", description: "Curated general vocabulary for daily use.", words: COMMON },
  { name: "IELTS Academic", description: "High-frequency academic words for IELTS.", words: IELTS },
  { name: "TOEFL Academic", description: "Advanced vocabulary for TOEFL preparation.", words: TOEFL },
  { name: "GRE Advanced", description: "Challenging vocabulary for the GRE exam.", words: GRE },
]

async function main() {
  console.log('🌱 Seeding LexiLearn database...')

  // Wipe existing data
  await db.delete(reviewLog)
  await db.delete(quizSession)
  await db.delete(srsCard)
  await db.delete(word)
  await db.delete(deck)
  await db.delete(appStat)

  let total = 0
  for (const d of DECKS) {
    const deckId = createId()
    await db.insert(deck).values({
      id: deckId,
      name: d.name,
      description: d.description,
      isCustom: false,
    })

    for (const w of d.words) {
      await db.insert(word).values({
        id: createId(),
        word: w.word,
        pos: w.pos ?? null,
        ipa: w.ipa ?? null,
        syllables: w.syllables ? JSON.stringify(w.syllables) : null,
        cefr: w.cefr ?? null,
        definitions: w.definitions ? JSON.stringify(w.definitions) : null,
        examples: w.examples ? JSON.stringify(w.examples) : null,
        synonyms: w.synonyms ? JSON.stringify(w.synonyms) : null,
        antonyms: w.antonyms ? JSON.stringify(w.antonyms) : null,
        etymology: w.etymology ?? null,
        amharic: w.amharic ?? null,
        deckId,
      })
      total++
    }
    console.log(`  ✓ Deck "${d.name}": ${d.words.length} words`)
  }

  // Initialize app stats
  const initialStats: Record<string, string> = {
    streak: '0',
    longestStreak: '0',
    lastSessionDate: '',
    totalXp: '0',
    dailyGoal: '20',
    ttsVoice: '',
    ttsRate: '1',
    theme: 'system',
    totalReviews: '0',
    totalCorrect: '0',
    achievements: '[]',
  }
  for (const [k, v] of Object.entries(initialStats)) {
    await db.insert(appStat).values({ key: k, value: v }).onConflictDoNothing()
  }

  console.log(`\n✅ Seeded ${total} words across ${DECKS.length} decks.`)
  console.log(`✅ Initialized ${Object.keys(initialStats).length} app stats.`)
}

main()
  .catch((e) => {
    console.error('Seed error:', e)
    process.exit(1)
  })
  .finally(() => {
    sqlite.close()
  })
